# Generated by Django 4.1.3 on 2022-11-08 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('rating', models.FloatField()),
                ('specialization', models.CharField(choices=[('General Doctor', 'General Doctor'), ('Emergency Doctor', 'Emergency Doctor'), ('Orthopedics Doctor', 'Orthopedics Doctor')], max_length=256)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('case', models.TextField()),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
            ],
        ),
    ]
