# Generated by Django 4.1.3 on 2022-11-07 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_doctor_experience_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='relation',
        ),
        migrations.AddField(
            model_name='appointment',
            name='relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
            preserve_default=False,
        ),
    ]
