# Generated by Django 4.1.3 on 2022-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Article', 'Article'), ('Opinion', 'Opinion'), ('Review', 'Review')], default='Article', max_length=64),
        ),
    ]
