# Generated by Django 4.1.3 on 2022-11-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='spcialization',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('heart and blood vessels', 'Heart And Blood Vessels'), ('Ophthalmology ', 'Ophthalmology ')], max_length=64),
        ),
    ]
