# Generated by Django 4.1.3 on 2022-11-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Relation_with_doctor',
            new_name='Doctor',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='DocSpecialization',
            field=models.CharField(choices=[('Obstetrics/Gynecology', 'Obstetrics/Gynecology'), ('Anesthesiology', 'Anesthesiology'), ('Cardiology', 'Cardiology'), ('Critical Care Medicine', 'Critical Care Medicine'), ('Dermatology', 'Dermatology'), ('Diagnostic Radiology', 'Diagnostic Radiology'), ('Emergency Medicine', 'Emergency Medicine'), ('Gastroenterology', 'Gastroenterology'), ('Family Medicin', 'Family Medicin'), ('Hematology', 'Hematology')], default='Anesthesiology', max_length=215),
        ),
    ]
