# Generated by Django 4.1.3 on 2022-11-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0002_rename_patient_appointment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointments',
        ),
    ]
