# Generated by Django 4.1.3 on 2022-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_rename_appointment_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Ear', 'Ear'), ('Nose', 'Nose'), ('Thraut', 'Thraut')], default='Nose', max_length=64),
        ),
    ]
